---
# tasks file for ansible-java

- package: name=wget state=latest

- name: Download Java
  command: 'wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-x64.tar.gz -P /tmp/'

- name: Create directory
  file: path={{ java_location }} state=directory mode=755

- name: Extract tar file
  unarchive: src=/tmp/jdk-7u80-linux-x64.tar.gz dest={{ java_location }} copy=no

- name: Add java to /usr/bin/
  alternatives: name=java path={{ java_location }}/jdk1.7.0_80/bin/java link=/usr/bin/java

- name: Add jps to /usr/bin/
  alternatives: name=jps path={{ java_location }}/jdk1.7.0_80/bin/jps link=/usr/bin/jps

- name: Create java home
  lineinfile: dest=/etc/environment line="export JAVA_HOME={{ java_location }}/jdk1.7.0_80"
